### PR TITLE
Optimize (lossless) all site images. -106.99 KB	

### PR DESCRIPTION
**Pull request by leighwilliams**

### CODE REVIEW

**Comment by eksperimental** [comment]
@leighwilliams did you use a command for this? I'm curious

**Comment by leighwilliams** [comment]
Hi @eksperimental.

I used https://kraken.io/web-interface.

**Comment by eksperimental** [comment]
cool. I did a bit of research, and  there's a tool called [pngcrush](http://en.wikipedia.org/wiki/Pngcrush)
that gets the job done. maybe that's the one they are using ....

**Comment by whatyouhide** [comment]
Great job @leighwilliams :+1:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by leighwilliams** [comment]
:smile: :heart:

**Pull request merged**
