### PR TITLE
Document packages precompiled against multiple OTP versions

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by josevalim** [comment]
As mentioned privately, I don't want to spread out release information between github and hexpm. Although I do like the fact the process can be automated.

**Comment by ericmj** [comment]
Just let me know how you want it. We can keep it undocumented/unofficial and just tell/send PRs to CI tools etc about how to use the builds. We can also document it on github.com/hexpm/bob which is more unofficial.

**Comment by josevalim** [comment]
Since the work is already done, we should at least document it in bob or
maybe even in Hex. Then we decide how to make it official.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Documented here instead https://github.com/hexpm/bob/blob/master/README.md#elixir-builds.

**Comment by eksperimental** [comment]
what about release candidates? are they supported by this?

**Comment by ericmj** [comment]
> what about release candidates? are they supported by this?

Yes, we provide builds for all git tags and branches in the repository.

**Pull request closed without merging**
