### PR TITLE
remove image and point to external host

### PR DESCRIPTION
**Pull request by kirkins**
#992

### CODE REVIEW

**Comment by eksperimental** [comment]
thank you @krikins
Just to be clear, who owns this server? The thing is previously the link to the course was changed, and now the image, we need to place it in a place where we know will stay permanently. thank you again

**Comment by kirkins** [comment]
@eksperimental the server is the same one linked to in the documentation. The original broken link was to someones personal dropbox.

**Comment by kirkins** [comment]
See line 88 where the book is linked to -> https://goo.gl/9w33lp

**Comment by josevalim** [comment]
Let's wait for a reply from @robconery please.

**Comment by josevalim** [comment]
Rob is ok with it, so let's host it ourselves as it is more fail proof.

**Comment by robconery** [comment]
Thank you! I can put the image online somewhere else if need be...

**Pull request closed without merging**
