### PR TITLE
Chapter about typespecs and behaviours

### PR DESCRIPTION
**Pull request by whatyouhide**
I stubbed a first draft of a possible chapter about behaviours. I saw that #31, the issue about such chapter, is quite old (mid 2012!), but it looks like it's never been tackled.

I pushed a "draft" commit, so that you can have a look at how things have came out. I'm actually not 100% sure you still need a chapter about behaviours (or **only** about behaviours, for that matter). I positioned the chapter as the last one (21) in the getting started guide navigation, but didn't actually number it (the file is called `behaviours.markdown` and the sections are numbered as `x.1` and `x.2`).

Let me know what you think of all this :smiley:. Thanks!

### CODE REVIEW

**Comment by josevalim** [comment]
Excellent, thank you! The main issue about behaviour though is that they require us to talk about typespecs. So a quick introduction to typespecs plus behaviours would likely be a great chapter, so +1 for this addition. We can place it after the sigils one.

**Comment by whatyouhide** [comment]
I agree 100% on combining typespecs and behaviours in a single chapters. I started with behaviours only since #31 is only about behaviours and #32 is about typespecs, so I assumed they should've been separate chapters. I'll try to make a draft of the "Typespecs and behaviours" chapter as soon as I can.

**Comment by whatyouhide** [comment]
I updated the chapter making it a chapter about **typespecs** and **behaviours**. I placed the chapter after the "Sigils" chapter, making it chapter 20. I also updated the chapter numbers and the navbar so that the "Where to go next?" chapter is now chapter 21.

I'm sure a lot of things can be written in a better way, so just let me know what you think for now :smiley:. Thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
