### PR TITLE
Getting started headings

### PR DESCRIPTION
**Pull request by eksperimental**
this removes the numbering from the headings (avoiding internal links to break over time)
and a lot of formatting fiddling in the Getting Started guide

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! Does this mean the headings will no longer be followed by their number?

**Comment by eksperimental** [comment]
yes. (I like it better with the numbers, but due to the limitations of being hosted in github pages)..
It will be good if we could do it in javascript.

**Comment by whatyouhide** [comment]
I'm not very :+1: on not having numbers before the section header. Doing in JS should be trivial, I'd be happy to do it by tonight if this gets merged soonish :).

**Comment by josevalim** [comment]
Awesome, I am merging this and then we can add the JS stuff.

**Comment by eksperimental** [comment]
sounds great, I realized "install" and "crash-course" needs to have the numbers removed.
thanks a lot @whatyouhide for joining in.

**Pull request merged**
