### PR TITLE
Getting Started: get rid of numeric pages

### PR DESCRIPTION
**Pull request by eksperimental**
Solves #442

All done (or almost).
the tree structure of the guides is all configurable in one file `_data/getting_started.yml`
from there the side bar is created, and the navigation for every page.
I have installed the [pageless-redirect](https://github.com/jekyll/jekyll-redirect-from plugin), it's a patched version from the PR in their github account.

you can see the redirection mapping in `_redirects.yml`
one improvement i made, is that `/getting_started/` redirects for the first chapter of the guide, and same for `/getting_started/meta/`, and `/getting_started/mix_otp`

I have put the site through a validator, and it's all good.
I checked all the links... there are a few dead links to fix (that's for another PR), but nothing introduced in these changes.
I uploaded it to my page, but it doesn't work since it runs on a subfolder.

please fetch this PR, and run `jekyll serve`

and thing we are all good.
The only repeated information is this

```
title: 13 alias, require and import
guide: 13
```

it's easier to load directly from the page.
We can still get rid of `guide:`,

And if a new page is introduced, we just need to replace 13, with 14 in the title and the headings for example `## 13.1 alias`

TODO: update all the links to avoid the redirection.

### CODE REVIEW

**Comment by eksperimental** [comment]
@whatyouhide if you want to download this pull request, do this:
```
git fetch upstream pull/443/head:page_names
git checkout page_names
```

**Comment by whatyouhide** [comment]
@eksperimental did you just delete all the files in the guides in 4d6d21f?

**Comment by eksperimental** [comment]
please, refetch, i just  pushed --force
5 minutes ago.
yeah. something was wrong with the first commit, files were deleted

**Comment by whatyouhide** [comment]
Looks nice. So there's no way to get rid of the `title:` and `guide:` metadata? Some way to infer them from `_data/getting_started.yml`? I always hated having to manually change chapter (and section) numbers.

I'm not familiar with Jekyll at all, that's why I'm just asking questions instead trying to solve this myself :). I don't know how Jekyll handles "helpers". If we could write our own helpers, we could avoid doing `## Section title` and write something like `<%= section('Section title') %>` so that section are automatically numbered.

**Comment by eksperimental** [comment]
as I mentioned before, we can get rid of `guide`,
We could leave guide at the `top`, ans reuse it along the artile, but i think it's better to have 
`## 13.1 alias`
than to have
`## {{guide}}.1 alias``
when you are in writing mode, i found it to be distracting all that.

same here. i don't know much about jekyll, just what i grasped from working on this website.
a solution like the one you proposed would be good.

**Comment by whatyouhide** [comment]
I prefer `## 13.1 foo` over `## {{guide}}.1 foo` too if we can't avoid writing the section number `.1` :). I've always used [Middleman](https://middlemanapp.com) as a static site generator and always found it much more lean and intuitive (also more Rails-like) than Jekyll.

I'd be happy to invest a couple of days into migrating the site to Middleman but I suspect @josevalim and the rest of the team wouldn't be happy with such major changes.

**Comment by josevalim** [comment]
Yes, let's migrate to `getting-started` and `mix-otp` too! Great, great work!

**Comment by eksperimental** [comment]
thank you Jose.
I think i'm done, for the first part
All links have been replaced, still the old links redirecting,
I have disabled the redirection temporarily (for testing purposes), and crawled the site, and no dead links, so we are good within the site even without redirection.
every single occurrence of "getting_started"  has been replaced with "getting-started", including filenames and folders
no dead links in the website, including external links (except for this one in docs: http://elixir-lang.org/docs/stable/elixir/Version.Requirement.html#t:t/0  that @josevalim  is taking care of).

It has been thoroughly tested, but since many changes and it has been automated, error may exist.
so please test.

All pages validate except for one little thing I will report later on (the attribute "X-UA-Compatible" not being recognized by the validator)

have a look guys and tell me what you think

**Comment by eksperimental** [comment]
There is one thing left, and is this: https://github.com/elixir-lang/elixir-lang.github.com/issues/442#issuecomment-72990075

I think it is important not to have numbers in the links, but unless we use a custom jekyll plugin, or hack the javascript that creates the TOC, we have to drop the numbers, at least in the subheaders..
if you are ok with that. Numbers look good before every heading,

**Comment by josevalim** [comment]
:heart:

**Comment by josevalim** [comment]
Let's proceed with the TOC changes too as you find appropriate!

**Comment by eksperimental** [comment]
alright, i will do those changes.

one problem: redirectionis not working
http://elixir-lang.org/getting_started/1.html

**Comment by eksperimental** [comment]
bad news!
github doesn' t support custom plugins. I totally overlooked this aspect
:-(

**Comment by josevalim** [comment]
No problem. Let's remove the custom plugin and use the redirect_from we mentioned earlier (which I have used in the past and it does work!).

**Comment by eksperimental** [comment]
let me try something easier. i will post a PR in 10 minutes.
and you tell me which one you prefer

**Comment by eksperimental** [comment]
yeah.. i don' t like much my solutions (I won' t even PR), https://github.com/eksperimental/elixir-lang.github.com/tree/page_names
it was createing a `/getting_started/` folder and holding all the redirect html files

I will proceed with `redirect_from`

**Comment by josevalim** [comment]
That's basically what redirect_from will do. Btw, can you send a pull request in two commits? One that removes the current plugin and another one that adds redirect_from? This way we can easily remove redirect_from changes in the future. :)

**Pull request merged**
