### PR TITLE
Add Sublime Plugin to Code Editor Support list

### PR DESCRIPTION
**Pull request by wsmoak**

### CODE REVIEW

**Comment by eksperimental** [comment]
Textmate bundle alwo supports sublim, i think it should be worth mentioning it

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by wsmoak** [comment]
@eksperimental the Textmate bundle is listed, and it's mentioned in the Readme for this one.  I think it does the syntax highlighting, and you need both.

**Comment by eksperimental** [comment]
@wsmoak yes, what i meant is that make a reference to sublimetext, where Textmate Bundle is listed,
what do you think @josevalim ?

**Comment by josevalim** [comment]
Yeah, we could call it Sublime / TextMate Bundle if it fits there.

**Pull request merged**
