### PR TITLE
clarify hidden points

### PR DESCRIPTION
**Pull request by mfrasca**
for people coming from object oriented languages, these points are quite tricky indeed.

### CODE REVIEW

**Comment by michalmuskala** [comment]
I wonder if it would maybe be easier to understand if regular atom was used as a name instead of the module-style one.

**Comment by mfrasca** [comment]
which would be the equivalent form? using anything else than `KV.SupervisorBucket` would remove the advantage of having uniform, predictable values for the atoms used as process names.

**Comment by michalmuskala** [comment]
You don't have this guarantee though. Anybody can use any atom as a name of any process.

**Comment by mfrasca** [comment]
that's very clear. and since we are defining names ourselves, we are free to fix our naming logic. I think this part was made explicit, when the documentation introduces the reader to naming processes.

**Comment by mfrasca** [comment]
or you would want to make it explicit in the supervisor-and-application page, near the first occurrence of `name:`.  but I don't think it would be necessary there.  I don't know.

**Comment by mfrasca** [comment]
later on in the page, there's this sentence: 
> `DynamicSupervisor.start_child/2` expects the name of the supervisor and the child specification of the child to be started.

and I'm perplex about the first parameter, the "name of the supervisor".  also `h(DynamicSupervisor.start_child/2)` doesn't say anything about the `supervisor` parameter.  

can we use also the supervisor `pid`?  or it really needs be the name?

**Comment by whatyouhide** [comment]
> also h(DynamicSupervisor.start_child/2) doesn't say anything about the supervisor parameter

Well, it links to the `Supervisor.supervisor/0` type which might be enough?

**Comment by mfrasca** [comment]
> Well, it links to the `Supervisor.supervisor/0` type which might be enough?

to me: no.  it didn't say anything to me.  I was also not aware of this `type` concept in Elixir, nor had I noticed the `t` help function in `iex`.

the second argument is described as `Supervisor.child_spec()`, but the documentation text is more explicit on what you are expected to provide.

maybe I just missed the knowledge "look up type definitions, using `t`".

**Comment by mfrasca** [comment]
(I'm afraid we aren't discussing the proposed change any more. my fault to open a side discussion.)

**Comment by josevalim** [comment]
Thanks @mfrasca. I have removed some of the discussion to before we write the code and clarified the text.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
