### PR TITLE
Self-host the images used in Learning Resources

### PR DESCRIPTION
**Pull request by dbbrian**
I found better quality images for most, it's a little heavier but it looks better.

### CODE REVIEW

**Comment by josevalim** [comment]
Cool, thanks! One last question: did you run [ImageOptimizer](https://imageoptim.com/) on them?

**Comment by dbbrian** [comment]
Done, -70k, nice. (I'd used the “Save for web...” previously)

**Comment by josevalim** [comment]
Can you squash the commits so we don't add the old versions to git history? Then this is ready to merge! Thank you!

**Comment by dbbrian** [comment]
Done, sorry! Mondays... ;)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
