### PR TITLE
File.close terminates its process.

### PR DESCRIPTION
**Pull request by mfrasca**
I think this is interesting to notice explicitly.

### CODE REVIEW

**Comment by mfrasca** [comment]
I see that you do mention it a bit below in the text.  maybe a forward reference?

**Comment by josevalim** [comment]
Oh, good find. If we are already talk about it, perhaps we can move the discussion down. Can you please update?

**Comment by josevalim** [comment]
I haven't reviewed this chapter in a while, so I decided to remove the more advanced parts too and focus on the important bits for now. Thank you! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mfrasca** [comment]
I found those "more advanced parts" quite interesting, I mean, there's so many ways to be a beginner, and in-depth materials can be eye openers.  it was already relegated into a "you don't want to know this" section.  anyhow, I hope you can use it somewhere else.  and I'll be very glad to know where that somewhere will be.  ciao, M

**Pull request merged**
