### PR TITLE
Rename to_char_list to to_charlist

### PR DESCRIPTION
**Pull request by kpanic**
Hi!
As far as I understand `to_char_list` is deprecated. I am renaming it to `to_charlist`

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by kpanic** [comment]
:smile:

**Comment by eksperimental** [comment]
great @kpanic, I forgot to add this to the TODO list when previous minor version was released.
thank you.

**Comment by kpanic** [comment]
@eksperimental no worries, pleasure!
I am re-reading the tutorial just for fun and that bit caught my eye ;)
Cheers!

**Pull request merged**
