### PR TITLE
some accessibility issues

### PR DESCRIPTION
**Pull request by lrosa007**
I was on the Elixir slack and saw a bot with a message about this: https://rocketvalidator.com/s/a1508cd6-02d1-4129-b8e8-4e0a7df109b5/p

Not sure how serious this is taken but I figured I might as well help considering the site is where I first started learning Elixir.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @lrosa007. I believe some of those have already been fixed. Can you please rebase your PR accordingly? Thank you!

**Comment by lrosa007** [comment]
Looking at recent commits shows me that most of what I have done is resolved already, sorry about that. I was doing this yesterday but never pushed it. If everything thing I did is already in then go ahead and close this. Sorry about that.

**Comment by lrosa007** [comment]
@josevalim ok, rebase is done. Looks like I managed to get in a title attribute into an iframe that wasn't there yet. Looks like this wasn't entirely useless.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
