### PR TITLE
Operator precedence

### PR DESCRIPTION
**Pull request by gwww**
Added page on operator precedence. It is reachable from the Getting Started / Basic operators page.

### CODE REVIEW

**Comment by ericmj** [comment]
This should just be on the operators chapter imo, no need for a special chapter.

**Comment by gwww** [comment]
Is that the Basic Operators chapter. Happy to put it there. What's the
consensus?

______
Sent using an itsy bitsy keyboard. Expect typos and brevity.

**Comment by josevalim** [comment]
Thank you @gwww! we will discuss the best place to put it there so you don't have to move things around multiple times. :D

**Comment by josevalim** [comment]
Merged manually, thank you!

**Pull request closed without merging**
