### PR TITLE
Getting Started guides in EPUB format

### LINKED ISSUE #860: Proposal: Getting Started Guide in EPUB Format
As a way to find new features for [BUPE](https://github.com/milmazz/bupe), I've been working on [elixir_getting_started_guide_to_go](https://github.com/milmazz/elixir_getting_started_guide_to_go), which is a module that converts the _current_ content of the [Getting Started Guide](http://elixir-lang.org/getting-started/introduction.html) into an EPUB document. According to [epubcheck](https://github.com/IDPF/epubcheck) the EPUB document is valid :)

What do you think of providing other formats of the _Getting Started Guide_?, here are some screenshots:

screen shot 2016-10-04 at 10 57 06 pm

screen shot 2016-10-04 at 10 57 26 pm

screen shot 2016-10-04 at 11 02 45 pm

Of course, there are some things to do, like improving the styles (help wanted) and at least include [highlight.js](https://highlightjs.org/) for the scripts, but first, I'll add the option to include custom CSS & JS in [BUPE](https://github.com/milmazz/bupe).

### PR DESCRIPTION
**Pull request by milmazz**
Fixes #860

### CODE REVIEW

**Comment by milmazz** [comment]
@dignifiedquire Thanks for your feedback.

@josevalim ping?

**Comment by josevalim** [comment]
@milmazz it is on my inbox but I have been busy, sorry. :S I will get to it hopefully soon.

**Comment by milmazz** [comment]
@josevalim no problem, take your time.

**Comment by JamesLavin** [comment]
@milmazz I just used this to generate the three guides. Very cool! Thanks for taking time to make this, Milton!

**Comment by milmazz** [comment]
@JamesLavin Glad to know you found it useful!

**Comment by milmazz** [comment]
@josevalim ping?

**Comment by milmazz** [comment]
I'll close this PR because it remained in the _Open_ state without activity for more than 60 days.

Feel free to re-open this PR if you want or you think is still relevant for this project.

**Comment by josevalim** [comment]
Sorry for the delay @milmazz :)

This is on my inbox. I remember about it every other day or so - and I will certainly get to it and figure out any loose ends.

**Comment by josevalim** [comment]
@milmazz btw, are you running some sort of script for doing this? I noticed this in ex_doc.

**Comment by milmazz** [comment]
> Sorry for the delay

@josevalim No problem. I just wanted to clean a bit my list of open pull requests.

> are you running some sort of script for doing this? I noticed this in ex_doc.

Oh no, that was the magic of <kbd>Ctrl</kbd> + <kbd>C</kbd>, <kbd>Ctrl</kbd> + <kbd>V</kbd>, and some sprinkles of laziness :laughing: 

A script that walk and close all your stale pull requests would be really nice, though.

AFAIK, with [probot-stale](https://github.com/probot/stale) you can accomplish something like that but per repository/project.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
Thanks @milmazz! I have cleaned up the source to remove things we don't need, such as CLI and mix tasks, and I think there are two remaining issues:

1. the kv-observer.png image that we use on the Supervisor and application chapter of the Mix and OTP chapter does not show up

2. Code highlight for IEX snippets do not work

Is there something we can do about those?

**Comment by josevalim** [comment]
[elixir-getting-started-guide.zip](https://github.com/elixir-lang/elixir-lang.github.com/files/1212197/elixir-getting-started-guide.zip)

**Comment by milmazz** [comment]
Definitely the problem has something to do with the way we build/load highlightjs, I did a [quick test](https://github.com/elixir-lang/elixir-lang.github.com/files/1212694/demo.zip) with a custom highlight version that I got [from their official site][highlightjs] and everything works like a charm.

The current JavaScript code (`assets/app-0cc3b4da6e.js`) in the EPUB document is minified, so, it's really difficult to know what is causing the problem. I'll investigate this issue tonight and I'll send a PR with the fix.

[highlightjs]: https://highlightjs.org/download/

**Pull request merged**
