### PR TITLE
Add a debugging chapter as part of the Getting Started with Elixir series

### PR DESCRIPTION
**Pull request by boddhisattva**
Addresses [this issue](https://github.com/elixir-lang/elixir-lang.github.com/issues/1065). Kindly note this PR is work in progress and is submitted in it's current state to get some initial feedback before more work can be done as part of the Debugging chapter.

### CODE REVIEW

**Comment by boddhisattva** [comment]
@josevalim and other collaborators of this project, I've started work on the debugging chapter with introducing `IO.inspect` for starters. Would be great to get your feedback on the contents for wrt `IO.inspect` before I proceed with working on other parts of the debugging chapter. Also, would it be feasible to do incremental merges to this chapter with each new debugger option added(as mentioned [here](https://github.com/elixir-lang/elixir-lang.github.com/issues/1065#issuecomment-353778003)) be a potential independent candidate(the candidates being: `:observer`, `:debugger` & `IEx.break!`)) that could be merged to this repo? This way what content is already ready can be made available to those who would be going through the Elixir getting started guides and they can hopefully find this info useful without having to wait for the whole chapter to be released to benefit from the content. I will most likely continue to work on these sections(one for  :observer, :debugger & IEx.break!) as and when I get time in the coming weeks.

There could be other things I could potentially be missing with incremental merges as well so happy to hear your thoughts to take things forward accordingly :) Thank you :)

**Comment by josevalim** [comment]
@boddhisattva we are a bit busy right now since we were getting 1.6 out of the door but my plan is to review your PR and the guides once things calm down a bit. Thanks!

**Comment by boddhisattva** [comment]
Totally understandable @josevalim 👍 . Thank you for your prompt response :) Happy to wait and follow up again after a few weeks.

**Comment by juhalehtonen** [comment]
I just read through the current WIP covering IO.inspect, and I think @boddhisattva has done a good job with introducing it through two easy-to-understand examples, and at I would be happy to see this made available on the website :)

As for your comment/question regarding incremental merges to this chapter, I started wondering whether it would be good to have a few other topics (at least :observer) covered prior publishing it or not. On the one hand, getting information to the people who read the docs swiftly is valuable in its own right, and I fully agree that having at least _some_ documentation available is better than having none. 

On the other hand, I started wondering whether leaving something as important as :observer out initially can backfire for those who read the docs before the expanded docs would be available, and would then assume that the Elixir debugging experience is limited to just using IO.Inspect without realizing that there's far more to it that just isn't covered. I admit that I only have a sample size of three people to go from, but everyone I know has only read the official docs through once before venturing elsewhere.

This isn't to say I'd be opposed to having the IO.Inspect made available as swiftly as possible (and I once again want to commend you on the work you've put in!), but rather just something that popped up in my head while reading through the commit and your comments :) So, any thoughts on this?

**Comment by boddhisattva** [comment]
@juhalehtonen Thank you for the kind words 🙏 and thank you also for taking the time out to review the content and share your feedback on the same as it helps me validate whether the content could help the intended audience or would I have to make some more changes before I proceed further.

I'm completely with you on the idea of providing at least 1-2 lines about the other debugging options( with relevant links) :). I think it would definitely be more helpful than just mentioning about `IO.inspect` alone as part of the initial version of the Debugging chapter.

I'm also happy to wait for other Elixir core team members to get back on this once they get time and we could definitely plan the next steps accordingly.

Thank you again for sharing your feedback :).

**Comment by josevalim** [comment]
This first draft looks great, thank you! :+1: Thank you!

I definitely think we need to cover `IEx.break! + IEx.pry`, `:observer` and `:debugger`. Also note we explore observer on the Mix and OTP guide. But a quick introduction here would help.

@boddhisattva if you want to tackle those other topics, it will definitely be welcome. Otherwise I will work on them right after merging this. :)

**Comment by boddhisattva** [comment]
@josevalim Thank you for the kind words 🙏 , I'm really glad to know it was worth the effort. I'm still a beginner to Elixir and I would end up taking more time on learning and experimenting with each of the other debugger commands. IMHO I think based on my current work, I wouldn't be able to work on them that swiftly and I believe it's in the best interests of the community to have them out earlier if you can work on them right after merging this as you've mentioned above :)

I'm really glad that there would be a Debugging chapter out that could help more people get up and running with Elixir faster! Thank you for your encouragement and support on this José  :)

**Comment by josevalim** [comment]
Merged manually and pushed, it is live! Thank you @boddhisattva for the great start!

**Comment by boddhisattva** [comment]
Thank you very much @josevalim 🙏  Really happy that this is now live!

**Pull request closed without merging**
