### PR TITLE
Update introduction.markdown

### PR DESCRIPTION
**Pull request by AstonJ**
Adding the Elixir Forum

### CODE REVIEW

**Comment by ericmj** [comment]
I think that list is only supposed to be for "official" places. Feel free to advertise the forum on mailing lists, IRC or Slack instead.

**Comment by eksperimental** [comment]
A new section could be created in the wiki https://github.com/elixir-lang/elixir/wiki

**Comment by AstonJ** [comment]
Sorry @ericmj, I thought the Slack channel was also a community initiative rather than an official space (since there is already an official IRC chat channel).

I also completely understand that there may be some apprehension because the Elixir Forum is so new, however, I genuinely believe it can offer tangible benefit to the community since it includes features and benefits that none of the current options do. A list can be found [here]( http://elixirforum.com/t/features-benefits-of-this-forum/131/2). 

Either way I am happy to go with whatever you decide - a new section in the Wiki sounds like a great place to include community initiatives such as this, @eksperimental :-)

**Comment by josevalim** [comment]
I will merge this and split it into official and non-official links. @AstonJ please consider adding a Code of Conduct to Elixir Forum. Feel free to use a variation of the one we use at elixir. I think it would be really useful to spread our values and our baseline for productive and respectful discussion.

Thanks everyone and have a great weekend!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
thanks @AstonJ for taking my suggestion into consideration,
I have updated the list https://github.com/elixir-lang/elixir/wiki#online-communities

**Comment by AstonJ** [comment]
Thank you @josevalim - you are awesome!!  

   

Yes of course we will add a CoC (in the form of a Mission Statement). We already have the bases covered in our fairly stringent TOU but the MS will, I hope, be a more personal note that better reflects you and the community you have created :smiley: 

Do you want me to email you (or Hugo) with a draft before it goes up?

Thank you too @eksperimental, the wiki looks good :+1:

**Comment by AstonJ** [comment]
Hi @josevalim, our [Mission Statement](http://elixirforum.com/t/our-mission-statement/141) is now up :smiley: 

In addition to our usual terms of use we are referring users to the Elixir CoC - which is actually very good! Much more positive and welcoming than others I have seen.

If you feel we need to amend something or want to draw our attention to anything in future, please don't hesitate to let me know. 

Thanks once again for everything, you are a real gent :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
