### PR TITLE
Update error message for unrequired modules

### PR DESCRIPTION
**Pull request by JagdeepSingh**
Elixir (1.3.4) gives the updated error message for un`require`d modules.

### CODE REVIEW

**Comment by josevalim** [comment]
This week we are releasing Elixir v1.4 which says:

```iex
iex(1)> Integer.is_odd(1)
** (UndefinedFunctionError) function Integer.is_odd/1 is undefined or private but Integer defines a macro with the same name and arity. Be sure to require Integer if you intend to invoke this macro
    (elixir) Integer.is_odd(1)
```

Maybe we should use that instead?

Thank you!

**Comment by JagdeepSingh** [comment]
Sounds good.

**Comment by josevalim** [comment]
Awesome, can you please amend your PR then? Then it should be good to merge!

**Comment by JagdeepSingh** [comment]
Ok. i will wait for the release and fix it then.

**Comment by josevalim** [comment]
v1.4.0 is out. :)

**Comment by JagdeepSingh** [comment]
Not needed now. The error message is correct on v1.4.0.

**Pull request closed without merging**
