### PR TITLE
Update dependencies-and-umbrella-apps.markdown

### PR DESCRIPTION
**Pull request by ashean**
Minor tweak to the wording. From:
_The caution here is to make sure the domains don't depended on each other (also known as cyclic dependencies)._
To:
_The caution here is to make sure the domains don't each depend on the other (also known as cyclic dependencies)._

### CODE REVIEW

**Comment by eksperimental** [comment]
@ashean "don't each" doesn't sound right to me.
I think the original phrase is pretty clear.

**Comment by ashean** [comment]
The issue I was trying to correct was the the "don't depend**ed** on each other". Depended is past tense so isn't correct in this situation. Actually, just dropping the "ed" yields a correct sentence:
The caution here is to make sure the domains don't depend on each other (also known as cyclic dependencies).

**Comment by josevalim** [comment]
@ashean awesome. can you change the PR to just drop the "ed" then? Thank you!

**Comment by eksperimental** [comment]
@ashean you are right. Yes, please just drop the "ed" then. cheers

**Comment by ashean** [comment]
Thats done now.

**Comment by eksperimental** [comment]
thank you @ashean

**Pull request merged**
