### PR TITLE
Add Elixir Koans as a learning resource.

### PR DESCRIPTION
**Pull request by Maikon**
PR to add the [Elixir Koans](http://elixirkoans.io) as a learning resource to the website.

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
The image is 201 KB, and it is 1881 px wide when we are only displaying 190px. It seems a lot for such a simple image (four or five colours).
Additionally you can use pngcrush or any online service such as https://tinypng.com/
to compress it even more.
That will improve loading times considerably

**Comment by josevalim** [comment]
Thanks @eksperimental. I force pushed this particular change and compressed the image. Then I went ahead and compressed all images on learning, we got to save about 300kb!

**Comment by eksperimental** [comment]
That's great, I see the image is now 17kb

**Pull request merged**
