### PR TITLE
add broken image on learning page

### PR DESCRIPTION
**Pull request by kirkins**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
What's the copyright of this image? If it's proprietary i guess it shouldn't be hosted here, and we should link from an external website same as we do with the book covers

**Comment by kirkins** [comment]
@eksperimental #993

**Comment by robconery** [comment]
Oh - ha! Bitten  by the Dropbox thing :). Yes this is fine thank you!

**Pull request merged**
