### PR TITLE
Changed reference to :timer.sleep to Process.sleep for 1.3

### PR DESCRIPTION
**Pull request by uri**

### CODE REVIEW

**Comment by whatyouhide** [comment]
👍

**Comment by josevalim** [comment]
Ship it!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
@josevalim no access to the website repo for me 😸

**Comment by josevalim** [comment]
@whatyouhide now you do :D

**Comment by whatyouhide** [comment]
Woot 🎉 Thanks, good day to be reviewing PRs today 😄

**Pull request merged**
