### PR TITLE
Fix function call example

### PR DESCRIPTION
**Pull request by aerosol**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by whatyouhide** [comment]
Are we sure it's not confusing if we show a call to `Orddict.new`, given that Elixir has no `Orddict` module?

**Comment by josevalim** [comment]
Let's use `Map` (Elixir) and `maps` (Erlang) modules?

**Comment by whatyouhide** [comment]
:+1:

**Pull request merged**
