### PR TITLE
Fix typo in Processes

### PR DESCRIPTION
**Pull request by wsmoak**
The phrase 'dozens of thousands' caught my eye.  How about this?

### CODE REVIEW

**Comment by eksperimental** [comment]
I think what the author meant was "tens of thousands",....

**Comment by josevalim** [comment]
Yes, let's please go with "tens or even hundreds of thousands"!

**Comment by wsmoak** [comment]
That makes more sense!  Fixed.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
:+1: that reads even better

**Pull request merged**
