### PR TITLE
1.3 lexicals

### PR DESCRIPTION
**Pull request by aesedepece**
Update for abiding by 1.3 lexicals' returned values:
https://github.com/elixir-lang/elixir/issues/4596
https://github.com/elixir-lang/elixir/pull/4629

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! Let's keep it around until 1.3 is out. :)

On Monday, May 16, 2016, Adán Sánchez de Pedro Crespo <
notifications@github.com> wrote:

> Update for abiding by 1.3 lexicals' returned values:
> elixir-lang/elixir#4596
> <https://github.com/elixir-lang/elixir/issues/4596>
> elixir-lang/elixir#4629 <https://github.com/elixir-lang/elixir/pull/4629>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/elixir-lang/elixir-lang.github.com/pull/748
> Commit Summary
>
>    - 1.3 lexicals
>
> File Changes
>
>    - *M* getting-started/alias-require-and-import.markdown
>    <https://github.com/elixir-lang/elixir-lang.github.com/pull/748/files#diff-0>
>    (21)
>
> Patch Links:
>
>    - https://github.com/elixir-lang/elixir-lang.github.com/pull/748.patch
>    - https://github.com/elixir-lang/elixir-lang.github.com/pull/748.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/pull/748>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
I'm kind of 👎 on the final section about these changes; they're not very prominent changes and I don't think they deserve a separate paragraph in the *getting started* guide. People reading this likely are starting with Elixir, so they likely won't care how this worked before (and it's a very small change anyways).

Also, personally I'd hold this change until 1.3 is released: again, people reading this guide are newcomers and they're likely not running on the master branch, so they will see different results.

We could just open an issue as a reminder/

**Comment by josevalim** [comment]
@aesedepece can you please remove the added paragraph and just keep the code sample changes so we can merge this now that 1.3 is out? Thank you!

**Comment by josevalim** [comment]
@aesedepece ping :)

**Comment by aesedepece** [comment]
Changed! Sorry for the delay.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
