### PR TITLE
mention IEx.Helpers.recompile

### PR DESCRIPTION
**Pull request by mfrasca**
I think this is the correct place to mention it, since it's the first time we start iex inside the project.

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mfrasca** [comment]
thanks for merging, but I have a perplexity here.
you removed the `()` after the function.
isn't this going to be deprecated soon?

**Comment by josevalim** [comment]
Good point. iex allows to invoke the helpers without parens but I would add
them here to avoid confusion.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mfrasca** [comment]
you know, the 'mention a function evaluates it', that's what kept me away from ruby.

**Comment by josevalim** [comment]
Yeah, in Elixir it only works without warnings inside IEx for convenience.

In any case, parens were added back in a more recent commit. :D

>

**Pull request merged**
