### PR TITLE
Add link to Collectable protocol documentation

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by link2xt** [comment]
This is the first time it is mentioned.

By the way, what is the policy on the links to documentation? Should it be only when something is mentioned the first time or does it make sense to add as many links as possible?

**Comment by link2xt** [comment]
@eksperimental Fixed it

**Comment by eksperimental** [comment]
I don't think there's such a policy but linking the first time it is mentioned it's good enough for me

**Comment by eksperimental** [comment]
Thank you @link2xt

**Pull request merged**
