### PR TITLE
Clarify that cond conditions can return any truthy value, not just `true`

### PR DESCRIPTION
**Pull request by Stratus3D**
Ran into an issue today, and when reading the docs I got the impression cond
looked specifically for `true`, and not just any truthy value.

### CODE REVIEW

**Comment by Stratus3D** [comment]
I'm not sure if the change to the first sentence in this PR is strictly required.

**Comment by josevalim** [comment]
Hi @Stratus3D!

We don't use the concept of truthy and falsy value anywhere else in the docs. So if we want to use it here, we would need to explicitly declare what it is before. We probably define the concept of `nil` and `false` being considered false at some point, so that would be a good opportunity to introduce said concepts.

**Comment by josevalim** [comment]
Ping.

**Comment by josevalim** [comment]
Ping.

**Comment by Stratus3D** [comment]
Sorry, I've not forgotten about this but I haven't had a chance to think about how this concept should be introduced. Should I add a paragraph on falsey and truthy values under the `cond` header?

**Comment by josevalim** [comment]
Perhaps? Another idea is to say any clause that doesn't return `nil` or `false`. And avoid the general truthy/falsy discussion for now.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
