### PR TITLE
added KV.BucketSupervisor to documentation

### LINKED ISSUE #1085: Dynamic Supervison page incomplete
On this page "The bucket supervisor" section is incomplete.
There is no KV.BucketSupervisor implementation.

### PR DESCRIPTION
**Pull request by sentyaev**
Closes #1085

### CODE REVIEW

**Comment by josevalim** [comment]
We don't need to define one. We can just start the DynamicSupervisor directly in our supervision tree, without defining a separate module for it. I will make it clearer in the guides, thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by sentyaev** [comment]
As I said I'm very new to Elixir and probably I doing something wrong, but I've tried follow this guide two times and without introducing `KV.BucketSuperviser` (when I just follow this guide) I receive this errors when I try to do `iex -S mix`:
```
** (Mix) Could not start application kv: KV.start(:normal, []) returned an error: an exception was raised:
    ** (ArgumentError) The module DynamicSupervisor was given as a child to a supervisor
but it does not implement child_spec/1.
```

**Comment by josevalim** [comment]
The guide requires Elixir v1.6.1, you are on Elixir v1.6.0. Your solution would work fine though if you don't want to upgrade. :)

**Pull request closed without merging**
