### PR TITLE
Added cheat sheet link.

### PR DESCRIPTION
**Pull request by benjamintanweihao**

### CODE REVIEW

**Comment by ericmj** [comment]
! think it's enough to mention the author by name and only add a single link to the cheatsheet. We already have a link to the OTP guidebook and this almost reads like an ad for it. Would be interested to hear what others think.

Thanks for creating this cheatsheet and providing it to the guide.

**Comment by josevalim** [comment]
I think the current links are fine, it is just the text style that feels ad-sy, but that's easy to change. Thank you @benjamintanweihao! :heart:

**Comment by josevalim** [comment]
Let me know what you think: https://github.com/elixir-lang/elixir-lang.github.com/commit/2062c0667eaba7010011e914ce7a9567a4be9694

**Comment by ericmj** [comment]
Looks great!

**Comment by benjamintanweihao** [comment]
Woot. Actually, I think we can remove the link to the book since as @ericmj has mentioned its on the site, and secondly it technically _isn't_ in the book :P

**Comment by josevalim** [comment]
@benjamintanweihao ok then, will do! :D

**Pull request merged**
