### PR TITLE
Fix a couple of typos

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by vais** [comment]
Please let me know if you want me to squash the two commits on my end - I should have known better than to edit directly in GitHub 🤦‍♂

**Comment by vais** [comment]
😅

**Comment by josevalim** [comment]
Thanks! No problem with multiple commits, we can squash via the github UI when merging!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
