### PR TITLE
Add new learning resource - elixir flashcards \0/

### PR DESCRIPTION
**Pull request by tetiana12345678**

### CODE REVIEW

**Comment by josevalim** [comment]
Awesome! Btw, we have been mostly keeping the list ordered according to when they are added, to avoid debates, so could you please make sure the cards are the last item in the section they belong to? Thank you!

**Comment by tetiana12345678** [comment]
oops. I got it wrong. I grouped flashcards together with books. Sorting function is not by paper 😆 Let me update

**Comment by tetiana12345678** [comment]
Do I need to squash commits?

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
