### PR TITLE
Correct types in sorting order

### PR DESCRIPTION
**Pull request by eksperimental**
based on 
https://github.com/elixir-lang/elixir/pull/5238/files#diff-50948d471af46f8f79bf8d175641fa42R67
by @fboyer

### CODE REVIEW

**Comment by eksperimental** [comment]
please let me know if you need the commits to be squashed

**Comment by whatyouhide** [comment]
Do we still need this in the guides @josevalim, or would it be wise to reword this chapter so that the heavy stuff is relegated to the Elixir docs?

**Comment by josevalim** [comment]
@whatyouhide I would still keep the ordering and say: "You don't need to memorize this ordering, it is enough to know an ordering exists. For more information, check the reference page on Operators."

Btw, what if we start calling the pages in the docs "Reference pages"? Since their goal is not to actually guide but provide a complete reference on a given topic?

**Comment by whatyouhide** [comment]
Yeah "Reference page" is a good description of what they are. So let's keep the ordering and write what you said, but let's merge this one like it is right? I can reword directly on master.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
