### PR TITLE
Adds support for Continuous Integration ( Overhaul of CI scripts )

### PR DESCRIPTION
**Pull request by eksperimental**
Overhaul of CI scripts from original PR #483 

Please feel free to review this one as I have made a lot of improvements, and documented code, as well as improved message the script to let useres customized the ERROR and SUCCESS messages (ie, number of errors, number of files with errors, number of files checked, links checked)

### CODE REVIEW

**Comment by eksperimental** [comment]
Jose, Is there any reason why we shouldn't have this ported to elixir code?
I just realized travis [supports elixir in beta mode](http://docs.travis-ci.com/user/languages/elixir/)

If you think it's a good idea, I will start working on it, since I need to start working on something real with elixir.

**Comment by josevalim** [comment]
It is up to you. If you think it works nicely for this task, why not? :)

On Monday, March 2, 2015, eksperimental <notifications@github.com> wrote:

> Jose, Is there any reason why we shouldn't have this ported to elixir code?
> I just realized travis supports elixir in beta mode
> <http://docs.travis-ci.com/user/languages/elixir/>
>
> If you think it's a good idea, I will start working on it, since I need to
> start working on something real with elixir.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/pull/485#issuecomment-76754888>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by eksperimental** [comment]
I think i'll give it a try then. and see how it goes.

**Comment by josevalim** [comment]
Closing this as it is out of date. :)

**Pull request closed without merging**
