### PR TITLE
Try Elixir Code School Course

### PR DESCRIPTION
**Pull request by bijanbwb**
### Notes

Code School has two upcoming Elixir courses! They're all set to launch next Tuesday on **February 21st, 2017**, and it would be nice to merge this in around that time.

Both courses will have full videos, slides, and interactive challenges. The first one is an introductory course called [Try Elixir](https://www.codeschool.com/courses/try-elixir), and then the second course called [Mixing It Up With Elixir](https://www.codeschool.com/courses/mixing-it-up-with-elixir) delves more deeply.

### Changes

This PR adds a small link to the Try Elixir course in the sidebar, and also adds the course as a resource on the Learning page. Feel free to make changes (copy, assets, styles, placement, etc.) or ask for adjustments and I'd be happy to follow up!

### Screenshot

elixir-lang

/cc @josevalim @caike

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks Bijan! Some feedback:

1. On the Learning section we have more of a reference of learning
resources... so a title such as "Try Elixir with Code School" may work
better. What do you think?

2. I would like to include a new section on the Learning page because
"Learn Elixir" is too broad now. I would like to focus it on books and have
a section for "Take Off with Elixir" and "Try Elixir with Code School"
which are more "Interactive" or "Video" based. Do you have a good idea on
how we should call this category?

3. For the sidebar, can you please move it after the "Join the Community"
section and before "Important Links"?

If you prefer for me to do those changes, please let me know and I can do
that before merging on 21st.



*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by bijanbwb** [comment]
Thanks for the quick review!

>1. On the Learning section we have more of a reference of learning
resources... so a title such as "Try Elixir with Code School" may work
better. What do you think?

Totally agree with this. I updated the title to "Try Elixir with Code School".

>2. I would like to include a new section on the Learning page because
"Learn Elixir" is too broad now. I would like to focus it on books and have
a section for "Take Off with Elixir" and "Try Elixir with Code School"
which are more "Interactive" or "Video" based. Do you have a good idea on
how we should call this category?

You're right that it would be nice to delineate between the book resources and
the interactive video-based resources. For now, I added a new category called
"Interactive Resources" and put both the Code School Try Elixir course and the
Taking Off With Elixir course in there too. I wonder if the Code School course
might be ideal at the top of the page since it's a quick interactive introduction
to the language, and then users can dive further with the book resources. Any
thoughts?

>3. For the sidebar, can you please move it after the "Join the Community"
section and before "Important Links"?

I updated the sidebar order so it should be all good. Feel free to tinker with
the spacing or placement though if you think it could use some improvements.

Thanks again and I'd be happy to follow up to keep iterating if there's anything
else we can do from over here on our end!

### Screenshots

screen shot 2017-02-13 at 12 59 37 pm

screen shot 2017-02-13 at 1 00 24 pm

**Comment by josevalim** [comment]
Looks great, thank you! Please give me a heads up when it is finally time
to merge. :)

**Comment by bijanbwb** [comment]
@josevalim We managed to soft launch our new [Elixir path](https://www.codeschool.com/learn/elixir) with both courses this morning! 🎉

Should be all set to merge this PR whenever you're ready. 🚀

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@bijanbwb I have deployed but the sidebar is not quite working. Can you take a look when you  have a sec please? Thanks!

**Comment by josevalim** [comment]
@bijanbwb nevermind, it was a caching issue. It should all be good now. :)

**Comment by bijanbwb** [comment]
😌 Looks good! Thanks for everything!

**Pull request merged**
